---
title: "Predicting level of partnership"
output: 
  html_document: 
    toc: yes
    toc_float: true
    theme: yeti
---

----


## Clients: 

* [Chico State Center for Healthy Communities](https://www.csuchico.edu/chc/)
* Cal Fresh Outreach Leadership Team: Brandi Simonaro, Aaron Kunst

## Data Science Student Team (DSST)

* Brandon Trahms
  - Liason 
  - Taskmaster
* Derek Borders
  - Oversight
  - Timekeeper


# Summary

# Project Goals

* Identifying common organizations that the subs partner with. 
    - Use text mining tactics to pull out key words from the text description to identify which are the common organizations that the subcontractors partner with (financial aid, EOP etc) without having to do a manual review of all entries. 
* Explore trends over time with regard to who campuses partner with during different parts of the academic year
* Create a model to predict partner level


# Timeline
_Details regarding deliverables to be added by DSST_

1. Expert CFO staff member fills in level of partnership for 10-20 records to serve as a time estimate for data labeling by 2/11/2022. 
    a. We will use that time estimate to decide if a smaller subset is necessary to reduce the burden of the CFO staff member, while allowing DS team to start working on the code for the prediction model. 
    b. The remainder of the records should be rated by 2/25/2022
2. 10-15 minute project check ins during class time approximately every two weeks starting 3/10/2022. The DS team will provide update the client on their progress with opportunity to ask questions from both parties. 
3. The CFO team will review a scientific poster created by the DS team for presentation at the College of Natural Sciences Poster Session, date somewhere in late April or Early May.  
4. The DS team will give a final stakeholder presentation to CFO team members/leadership during the week of May 15th, 2022 (Finals week). 


# Domain learning

* https://www.csuchico.edu/chc/
* https://www.chicostatecalfresh.org/
* https://www.canr.msu.edu/news/five_levels_of_community_partnerships

----

# Project Updates
_Weekly updates done by DSST via PR_

## 03/02/2022  

### Milestones

- Open dialogue with client.  
- Obtain initial few labeled rows.


## 03/09/2022  

### Milestones 

- 

## Ongoing  

### Next Steps  

- Complete Data Security Training
- Follow up with sponsor. 
  - Clarify Goals
  - Clarify Levels
  - Discuss potential avenues of exploration. 
  
- (Brandon) Refactor prior work and data to work/knit w/o box access. 

- (Derek) Come up to speed on past project work. 

- Review literature.

- Review sentiment analysis techniques.
  
### Potential Upcoming Paths  

- Create model to classify individual meeting instances
  
  - Get labeled keyword list OR
  
  - Generate common word list and ask for labels on top words
  
- Use model to label all activity rows in dataset, find least certain generated labels, get sponsor clarification, input result, iterate model.

- Predict (infer?) level of partnerships over time (subcontractor + partner by quarter). 

- Track overall performance of subcontractors and partners. 




 

