```{r, echo=FALSE, message=FALSE, warning=FALSE}
wk1.date <- as.Date("2020-01-21")
```

This is the course website for <span style="color:blue">**MATH/CSCI 485 - Advanced Data Science**</span> course taught by [Dr. Robin Donatello](www.norcalbiostat.com) in Spring 2020 at California State University, Chico. This landing page is used for posting of regular announcements and information for students of the class. 

_This course aims to help students navigate the evolving and murky waters of the Data Science landscape. We do so by not only providing training in advanced programming and technical skills, but also by providing opportunities for collaboration with other disciplines and reflection on how Data Science impacts human society._

> Due to the COVID-19 pandemic all classes will be held online for the remainder of the semseter. 

----

### `r format(wk1.date+6*8, "%m-%d-%Y")` Week 9: Introduction to Natural Language Processing

* Project updates, starting to talk about NLP. 
* New course note format to reflect the online delivery. 
    - See [these notes](lec/week9-notes.html) to begin. 
    - A recording of these notes will be put into Google Drive. 

----

### `r format(wk1.date+6*8, "%m-%d-%Y")` Week 8: Translating a scientific question to a data analysis plan. 

Crazy week with COVID-19 ramp up. 
See Google Drive for class notes. 

> Update - these have been moved into lecture notes. See the [materials](materials.html) page. 

----

### `r format(wk1.date+6*7, "%m-%d-%Y")` Week 7: Statistical Learning

     
* We will learn out of the ISLR textbook in several ways such as;  
    - I will pose a list of questions and assign them for you to answer/share with the rest of the class. (See hw05 as an example)
    - Selected exercises from the back of the chapter.

There are supplemental videos and slides for the ISLR textbook. Links are on the [materials](materials.html) page. Me passively lecturing is not the best way for you to learn. I am trying to include you all in as much of the learning process as possible. 

We will not cover ISLR Chapter 3: Linear Regression in much detail, as that is one of the main topics in 456. This however is a **GREAT** chapter to read for a different perspective/approach to regression. `r emo::ji("star")` `r emo::ji("star")``r emo::ji("star")``r emo::ji("star")``r emo::ji("star")`. Highly recommmend. 

----

### `r format(wk1.date+5*7, "%m-%d-%Y")` Week 6: Case Studies in Data Science

Examples in Data Science
  - You will share your case study/chapter in DDS with the rest of the class. 
  - Prepare to only talk for 7-10 minutes on your chosen chapter/case study. If you have more info 
    to share, consider writing up your notes in HackMD and we can add it to our shared notes files.
   

----

### `r format(wk1.date+4*7, "%m-%d-%Y")` Week 5: Doing Data Science

* Being a Data Scientist means more than just building models. It's identifying what the customers need, what they currently have, and how to bridge that gap. We'll be working on case study in class this week. 

* On Thursday we're going to share out case studies from the DDS book. Please respond to the Slack Poll in `#readings` by EOD on Tuesday (2/18) for which chapter you're going to read & share on Thursday (2/20). 

* You also need to review another teams R Twitter data tutorial. Everyone has read access to all tutorial repos. Use GitHub **issues** to make comments/suggestions.  Things you are to look for: 

    1. Terminology not defined / too technical. Doesn't look like standard R help files. 
    2. Instructions start off at an appropriate point, assuming they have installed the `Rtweet` package but have not loaded it. 
    3. Code needs to be able to run independently, without a Twitter account. 
    4. Examples of what the data looks like. 
    5. Suggestions on how to use the data / what analysis questions could be asked with this data. 


* Dates
    - Peer Review due Thursday 2/20
    - Final version due Sunday 2/23
    - I will present your tutorials to the POLS class on Wednesday 2/25 along with providing them a sample data set containing historical tweet data. 

* POLS project dates are starting to be set. See google calendar for a general idea of project timeline. More info will be posted on the Project page in the next week or so. 


----

### `r format(wk1.date+3*7, "%m-%d-%Y")` Week 4: POLS Twitter analysis project

Housekeeping

* Assignment tracker in google drive
* HW02 collab notes - getting started. We *will* learn machine learning. It's not as mystical as you think it is.  

This week we will explore the following questions: 

* What types of analysis can be done on Twitter data? 
* What types of analysis are important in the field of political science / public administration / public opinion? 
* HW03 involves team writing a tutorial for the POLS students. We'll work out how to form teams in Github in class. 
* You're advised to finish all Twitter assignment items before 

----

### `r format(wk1.date+2*7, "%m-%d-%Y")` Week 3: POLS Twitter analysis project 

* POLS project page has been updated. 
* Read over the [Hack MD notes/idea](https://hackmd.io/@norcalbiostat/data485-twitter) dumping ground
* Make a Twitter dev account before Tuesday. (docs are in the hack md post)
* Read over the summary of DS project examples (POLS google drive)
    
Thursday I will be in a teaching demo from 2-2:50pm. You are expected to come to class and work together. 
I will come check in with you all when that class is over. 

----


### `r format(wk1.date+1*7, "%m-%d-%Y")` Week 2: What is Data Science? 

* Websites
    - We'll finish our introduction to working with `blogdown` to make dynamic websites. 
    - Then you need to start working on creating your own personal page. Deadline for a site with just the basic info (HW1) pushed back to Friday. 

* What is Data Science
    - We'll explore the world of DS a bit more in depth, using HackMD as a place for our collaborative notes.
    - Read DDS Ch 1 and 16 to provide background and context

* What is your DS Niche? 
        - What is your skillset? Your domain? 
        - Where do you want to grow? 

----

### `r format(wk1.date, "%m-%d-%Y")` Week 1: Welcome to Spring 20!

This course website contains all materials except the textbooks for this class. Be sure to familiarize yourself with the organization. You will be here a lot. Bookmark this page.

Invitations to a Slack workspace will have been sent out to your @mail.csuchico.edu email address. 

