---
title: "DATA 485 Schedule"
output: html_document
---
<br> 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(kableExtra);
options(knitr.table.format = "html", knitr.kable.NA = '') 
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
```

# _Last Updated: `r format(Sys.time(), "%a %b %d %X")`_ {.tabset .tabset-fade .tabset-pills}

## Schedule 

```{r}
# Read in schedule
raw_detail <- read_excel("schedule_485.xlsx", sheet="schedule")

cdat <- raw_detail %>% mutate(Date = format(date, "%m/%d"))

#cdat$Assignments <- gsub(" (", " <b> (", cdat$Assignments, fixed=TRUE)
#cdat$Assignments <- gsub(" )", ")</b>", cdat$Assignments, fixed=TRUE)
```

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
out <- cdat %>% select(Week, Date, Topic, `Learning Objectives` = SLO, Prepare, Notes)

knitr::kable(out, align="cclll", escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered"), 
                position='center') %>% 
  column_spec(1, width="5%") %>% 
  column_spec(2, width="5%") %>% 
  column_spec(3, width="20%") %>% 
  column_spec(4, width="30%") %>% 
  column_spec(5, width="20%")  %>% 
  column_spec(6, width="10%") 
```

## Deliverables

_Todo: Display as DT so can filter on week or due date._

```{r}
tasks <- read_xlsx("C:/GitHub/ADS/schedule_485.xlsx", sheet = "assignments", 
          col_types = c("numeric", "numeric", "text", "text", "text", 
                        "text", "date", "numeric"))

tasks %>% 
  filter(!is.na(order)) %>%
  select(-order, -pct_effort) %>% 
  kable(align="l", escape=FALSE) %>% 
   kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered"), 
                position='center') %>% 
  column_spec(1, width="5%") %>% 
  column_spec(2, width="10%") %>% 
  column_spec(3, width="30%") %>% 
  column_spec(4, width="5%") %>%
  column_spec(5, width="10%")  %>%
  column_spec(6, width="5%")
```



