---
title: "Syllabus for MATH 485 - Spring 2022"
output: 
  html_document: 
    toc: yes
    toc_float: true
  css: style.css
---

# Logistics

* **Course Name:** Advanced Topics in Data Science (a.k.a. ADS or DATA 485)
* **Instructor:** Dr. Robin Donatello  (Dr. D, she/her)
* **Office Location:** Holt 202
* **E-mail:** rdonatello@csuchico.edu
* **Best Contact Method:** Discord
* **Office Hours:** TBD Week 2
* **Meeting time and locations:** TR 9:30-10:45 pm Butte 203, or remotely over Zoom as needed. 
* **Prerequisites:**
    1. Introduction to Data Science (DATA 385).
    2. Math 456 (_or co-requisite_)
    3. Or instructor permission
* **Course Website:** https://data485.netlify.app/
* **Discord Server**: https://discord.gg/tzcB4MJadW

## Required Materials

* **Computer**
    * A laptop is nearly invaluable, bring to class every day. 
    * A solid internet connection is a must. We will be using a lot of online resources.
* **Computer Software**: R 4.1+, RStudio 1.4+, git, Discord. 
* **Accounts (Free)** Github, Discord
* **Textbooks** 
    * Introduction to Statistical Learning (ISLR) [[PDF]](https://www.statlearning.com/) [[Slides & Videos]](http://auapps.american.edu/alberto/www/analytics/ISLRLectures.html), [[Code]](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html)
    * Doing Data Science (DDS), Cathy O'Neil, Rachel Schutt (2014) ISBN-10 978-1-449-35865-5 [[Library copy]](https://csu-chico.primo.exlibrisgroup.com/permalink/01CALS_CHI/s3tu53/alma991071823573402901)
    * Benjamin, Ruha. Race after Technology: Abolitionist Tools for the New Jim Code (RAT). Polity, 2019. ISBN 978-1-509-52643-7. [[Library copy]](https://csu-chico.primo.exlibrisgroup.com/permalink/01CALS_CHI/s3tu53/alma991008332949602904)

---

# What are we going to learn? 

## Course Learning Outcomes

By the end of the course, students will be able to...

1. Work effectively with a remote team using modern collaboration tools.
2. Build and update a professional online presence.
3. Explain how modern automated technology can perpetuate existing structures of discrimination through its design and application.
4. Train and validate a variety of predictive and classification models. 
5. Professionally engage with a client to assess and potentially solve a problem using data science tools within the framework of the data science lifecycle


## General Outline of Topics
Totally subject to time constraints and how the class unfolds, but generally be covered in the following order. More details are on the schedule page of the course website. 

1. Creating personal webpages. 
    - You'll be heading into the career world soon enough. Now is the time to start playing around with your own site and building your DS portfolio. 

2. What is Data Science? Who is doing Data Science? What's hot right now? 
    - Another look at the field you are studying. 
    - Building connections into this community. 
    - What is your Data Science profile? 
    
3. SQL - because you got to learn this at some point. [[All you really need to know about SQL in one tweet]](https://twitter.com/thosjleeper/status/1184572652125589504?s=09)

4. Statistical Learning
    - Linear Regression, from a different viewpoint
    - Classification using multiple classifiers
    - Resampling methods (Cross Validation)
    - Tree based methods
    - Unsupervised clustering

5. Ethics of Algorithms, Machine Learning, Big Data. 
    - Lots of reading, reflection, and looking for examples in every day occurrences. 
    
----
  
# Who are we learning it with? 

My name is Robin Donatello and my pronouns are she/her. You can address me as "Robin", "Dr. D", or some other respectful title such as "professor". 

I am a first generation college student who started at Butte College, double majored in Statistics &  Biology, with minor in Chemistry here at Chico State, and ended with a Doctorate in Public Health (DrPH) Biostatistics from UCLA. 

My campus life consists of training the next generation of Scientists how to harness the power of Statistics and Data in a responsible and ethical manner, supporting students in their academic adventures through intensive advising and research, leading the Data Science Initiative (DSI) to develop Data Science capacity on our campus, and providing analytical support and statistical consulting for many projects on and off campus.

When I’m not on campus, typically I’m growing 🥕🌾🍅🍆🍏 for my family, out adventuring with my 🐶🧔🐩, or getting some 🎮🎲📚 time in.

You can learn more about the work that I do on my [website](http://www.norcalbiostat.com/)

----

# How are we learning it? 

This class is semi-unstructured, meaning there is a combination of standard homework assignments, and several ongoing / multi-stage activities that we'll be working on throughout the semester. A lot of class time will be spent working on activities. 

* **Textbook assignments** We will be working through ISLR to learn and practice predictive modeling using typical problem sets. 
* **Collaborative note taking** You will collaborate to generate class-wide course notes and materials. 
* **Reading & Reflecting** We will engage with several readings where you will be asked to answer reflection questions in your personal learning journal, as well as having discussions with your peers. 
* **Peer feedback / code review** Reviewing each others work and code facilitates the sharing of knowledge, strengthens your ability to read others work, and can find bugs and problems early in the development stage. 
* **Interdisciplinary Collaboration Project** We will be collaborating with two campus organizations to provide data and research assistance. Details about the projects will be discussed in class and posted on the course website. 

----

# How is learning measured?

In the workplace you don't get homework assignments. You work on larger projects typically broken down into smaller pieces with their own due dates. It is common also to be working on multiple projects at the same time. 

The learning objectives for this class are very broad and high level. To work towards achieving those goals you will have several tasks to work through each week. Depending on the effort level for each task, the actual number of tasks will vary. 

There are five general areas that each task is designed to help strengthen. 

* Skills: Can you do the thing? 
* Communication: Can you talk about the thing? 
* Knowledge: Do you understand the thing? 
* Collaboration: Can you work on the thing with someone else? 
* Learning: What did you learn from engaging with the thing? 

I will review your work and provide feedback as appropriate. To acknowledge that revision and growth is part of every aspect of our lives, that we all are balancing other external priorities and that nothing is ever perfect, I use an effort based scoring method. 

Each task will be classified as incomplete (0) / needs major revision (0.5) / complete (1). You will then be given a score for the week calculated as `completion status * % effort` summed over all tasks. Scores will be scaled to 10 points for ease of addition. 


## Grading

- A dataset of tasks with completion status, % effort and a script that generates your weekly and overall scores will be available in a private github repo that is updated regularly. 
- I mostly stick with the standard grade cutoff ranges of 100-90%: A, 89-80%: B, 79-70%: C, 69-60%: D, 0-59%: F, but reserve the right to modify those ranges depending on how I feel the semester went.
- I also reserve the right to round a grade up up if borderline (i.e. 89.6% to a 90%) based on in-class attitude and general engagement in the class. 

---

# Class Policies and statements

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

-  Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. I make it a point to call on people by name, so please make sure that I know what you want to be called. 
        - I also want to try to pronounce your name as accurately as possible. The more you help and correct me the better I can do to honor your name. 
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback using the feedback button on the schedule and help pages of the website (which will lead to me making a general announcement to the class, if necessary to address your concerns).
-   If you prefer to speak with someone outside of the course, the Office of Diversity and Inclusion is here to assist. Their number is 530-898-4764, and email [diversityoffice\@csuchico.edu](mailto:diversityoffice@csuchico.edu){.email}
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).

*Adapted from [Monica Linden at Brown University](https://www.brown.edu/sheridan/teaching-learning-resources/inclusive-teaching/statements)*.

Furthermore, I would like to acknowledge that Chico State stands on lands that were originally occupied by the first people of this area, the Mechoopda. I recognize their distinctive spiritual relationship with this land and the waters that run through campus. I am humbled that our campus resides upon sacred lands that once sustained the Mechoopda people for centuries.


## Attendance

This is a fully in person class, however time has shown us that we need to be flexible and be able to go online at anytime. There may be times we want/need to hold/attend class remotely.  

Class attendance is expected. Talk to me ahead of time if you need to miss a class for a planned reason. In the event of an unplanned reason, PM me in Discord when you can so that I know you are still alive. 

* If you are not feeling well or are experiencing COVID symptoms **DO NOT COME TO CLASS**. DM me in Discord and attend online until you can return. 

## Zoom Eqituette

When we meet online please attend to the following

-   **Location**: I don't really care where you're at, as long as you're not lying down and falling asleep.
-   **Camera**: On is my preference as it helps to foster connections. I acknowledge that personal/bandwidth limitations do exist and there may be times where you need to turn off the camera. It is recommended that you use a blurred or virtual background as needed for privacy. 
-   **Microphone**: Keep yourself muted unless sharing out as a way to keep background noise to a minimum.
-   **Food/drink**: No problem. Just no see-food.
-   **Kids/Pets**: Yes please! Pet visits are especially encouraged, but we must get introductions.

----

# Campus Resources

This [campus website](https://www.csuchico.edu/coronavirus/students.shtml) contains a lot of information and resources specific to our COVID-19 situation. Specifically this page contains links to resources to help you keep [learning](https://www.csuchico.edu/keep-learning/index.shtml), and [engaging](https://www.csuchico.edu/keep-engaging/index.shtml), and lots of links to student support services such as emergency grants, basic need such as healthy food and housing, tutoring, health center, financial aid and a lot more.

## Technology Support

-   [IT Support Services](https://www.csuchico.edu/itss/) will provide comprehensive technology support, including laptop loans and virtual technology assistance.
-   The [Office of Accessible Technology Services](https://www.csuchico.edu/oats/) will offer all students online access to a staff member during normal business hours Monday--Friday via email at [oats\@csuchico.edu](mailto:oats@csuchico.edu). Students with questions on inclusive technology or who need assistance setting up technology accommodations are encouraged to reach out.
-   If you do not have off-campus access to the Internet, [resources are available](https://www.csuchico.edu/coronavirus/internet.shtml).
-   The [Data Science Initiative](https://www.csuchico.edu/datascience/) offers year-round training workshops and seminars on data-science related topics including R.
-   [Community Coding](https://www.csuchico.edu/datascience/community-coding.shtml) (CC): Students, staff, faculty, and the public are invited to join the Community Coding sessions. Bring your computer, coding projects, and your questions to this open working environment. Think of CC as additional office hours where you have access to more teachers than just me.

## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness, or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations. We try our best to ensure equal access to materials in accessible formats. Reach out to your me if there is some aspect of the course materials that are inaccessible to you.

Accessibility Resource Center 530-898-5959 Student Services Center 170 [arcdept\@csuchico.edu](mailto:arcdept@csuchico.edu){.email} [http://www.csuchico.edu/arc](https://www.csuchico.edu/arc/)


# University Policies

## COVID-19 

The CSU requires students to be fully vaccinated and boosted against COVID-19 by February 28th, 2022, unless you have an approved exemption.  Additionally, Chico State is requiring everyone on campus to wear an approved face covering in all indoor campus spaces. Accordingly, all students are required to wear an appropriate face mask covering the nose and mouth in order to participate in this course. Policies and requirements regarding COVID-19 are subject to change pursuant to campus, local, state and/or federal guidelines.

Please note that dishonesty relating to the vaccination policy and/or your failure to comply with any other COVID-19 related safety policy or mandate, including the face covering requirement, may result in disciplinary action against you through the office of Student Conduct, Rights and Responsibilities, which can include suspension or expulsion from the California State University system. 

Individuals unable to wear a face covering due to a medical condition should contact the Accessibility Resource Center by phone at (530) 898-5959 or by email at arcdept@csuchico.edu. 


## Adding and Dropping the course

You are responsible for understanding the policies and procedures about add/drops, academic renewal, etc., found in the [CSU Chico University Catalog](http://www.csuchico.edu/catalog/). You should be aware of the deadlines and penalties for adding and dropping classes.

## Confidentiality and Mandatory Reoprting

As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility related to my role as a your instructor. I am required to share information regarding sexual misconduct with the University. Students may speak to someone confidentially by contacting the Counseling and Wellness Center (898-6345) or Safe Place (898-3030). Information on campus reporting obligations and other Title IX related resources are available here: www.csuchico.edu/title-ix.


## Academic Integrity

Academic integrity is defined as “a commitment, even in the face of adversity, to five fundamental values: honesty, trust, fairness, respect, and responsibility”. From these values flow principles of behavior that enable academic communities to translate ideals to action. Academic integrity is expected and required. No forms of cheating or plagiarism will be tolerated. Please see your student handbook at https://www.csuchico.edu/scrr/integrity.shtml if you have questions about the meaning of these terms or the consequences of violating academic integrity.

-----

_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_
