---
output:
  html_document:
    toc: yes
    toc_float: yes
title: "Week 1: Jan 23 - Jan 29"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_485.xlsx")
week.w <- filter(raw, Week==1)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
tue    <- t(str_split(week.w$Tuesday, "\r\n", simplify=TRUE))
thu    <- t(str_split(week.w$Thursday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```

# How to Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```

----

# Tuesday: `r topics[1]`

```{r}
kable(tue) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```

----

# Thursday: `r topics[2]`

```{r}
kable(thu) %>% kable_styling(bootstrap_options = "striped", full_width = F, position="left")
```


