---
title: "Week 7: Linear Regression"
date: "`r paste(Sys.Date())`"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
    toc_depth: 2
always_allow_html: true
---


# Housekeeping 

We will not cover ISLR Chapter 3: Linear Regression in much detail, as that is one of the main topics in 456. This however is a **GREAT** chapter to read for a different perspective/approach to regression. `r emo::ji("star")` `r emo::ji("star")``r emo::ji("star")``r emo::ji("star")``r emo::ji("star")`. Highly recommend. 

[[Full YouTube playlist]](https://www.youtube.com/playlist?list=PL5-da3qGB5IBSSCPANhTgrw82ws7w_or9)

----

# Learning Path

### Where we've been

### Where we're at

### Where we're going

### Learning Objectives

----

# Tuesday

* Reading discussion: Engineered Inequity
* Open work day

----

# Thursday

* Project client share out. Prepare a 10 minute presentation to the class and your client on the status of your project. 

----

# Assignments

## Learning Tidymodels

Create a new Rmarkdown file and walk through Tidymodels tutorial [Preprocessing your data with recipies](https://www.tidymodels.org/start/recipes/)

Don't just copypasta the tutorial. This is your learning & practice notes file. Write notes to yourself on what you are doing and why.

## Write a Regression tutorial

Leverage your knowledge of linear models and write a tutorial on how to fit a regression model in the Tidy models framework. The data and model you fit is your choice. 

Ref: [ISLR Tidymodels lab for Chapter 3](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/linear-regression.html). 

Post your tutorial URL in Discord. 

## Peer review
You then are asked to review another classmates tutorial and provide comments & feedback in Discord. Is there something that isn't clear? Did you spot a mistake they can fix? What did you find helpful & useful about their tutorial (be specific). 

Do this as a reply to their tutorial URL post so your replies are easy to find. 
  
  


