---
title: "Welcome to Advanced Data Science (Sp20)"
output:
  html_document:
    css: ../style.css
---

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _

## About me. 

* Biology major who got turned to the fun side of Statistics while at Butte College
* Double major Biology, Statistics, Minor in Chemistry (Domain knowledge ftw), CSU, Chico
* MS Biostatistics (UCLA), thought i'd only be there for 2 years but..
* DrPH Biostatistics (UCLA) ... it was just to much fun. 
    - DrPH: Doctor in Public Health. I have more training in the Public Health/Medical sector than your average Statistician. More breadth, 2 fewer deep Stat theory classes. 
* Worked as a Data Team lead for a Teen pregnancy prevention programs - still collaborate with them. 
* Always loved statistical computing
    - Cobol at Butte College
    - Online Text based RPG (MUD) world builder
    - SAS at Chico
    - Stata, R at UCLA
* **Lucked out** and saw this Stat faculty position back at Chico, applied, and came back home. 
* Hired to specifically build a Data Science program
    - Didn't intend to be a teacher, but wanted to be in Chico, and I love to share knowledge and show people neat things
    - Fondness for training the next generation of awesome scientists has been an unexpected area of professional growth. 
    - Still learning how to be an effective teacher. 
    - Note my lack of formal training in Computer Science
    - Certificate program is an initial start, a place to get our feet wet and to try things out. 
    

_Important: A measure of patience with me is required._

* I may be behind in getting items posted and/or graded.   
* I am still struggling with some of the more CS skilled topics as well.  
* Second time teaching this class, 2 years ago.  
* Links on this page may be broken (submit a PR to fix!)_


> Who are you? 

--- 

## Let's get started. 

1. Start a learning journal. This can be on paper, or online such as Google Docs. You will be doing another for Math 456, so keep this one separate. I will be checking in on it regularly. 
2. [3-2-1 Bridge Activity](https://norcalbiostat.github.io/MATH315/lecture/321_Bridge.html)

---

## Course Description

This course aims to help students navigate the evolving field of Data Science. We do so by not only providing training in advanced programming and technical skills, but also by providing opportunities for collaboration and reflection on how Data Science impacts human society. The overarching themes of the class include the following. 


### Collaboration
* Team collaboration tools (Slack, Zoom, Github)
* Joint project with Political Science Graduate students
* Community Coding 
    - required to attend at least X times. 
    - Might as well sign up for MATH 290 and get a unit out of it (and help us get $$ to fund the class)
* [DATAFEST](chicodatafest.netlify.com)!! April 17-19th. 
    - Required at some level. Either participate or consult. 
* What's your Data Science Profile?

### Computation 
* Identifying and applying appropriate methods to answer a business or research need. 
* Introduction to Statistical learning / Machine learning techniques
* Parallel Processing
* Neural Networks, Deep Learning, Image Classification

### Communication 
* Effectively communicating your results is necessary for adoption and further development. 
* Dissemination of reproducible, transparent research.
* Writing instructional materials (tutorials) for others to learn things.  
* Reflections and discussion on readings, interesting findings
* Peer review

### Community 
* Building a professional online presence
* Social Media for #DataScientists 
* Who's out there doing cool things? 
* Keeping current with a fast moving field. What's next on the Hype Cycle?

### Conscience 
* Ethics of predictive analytics (Weapons of Math Destruction)
* Protecting privacy in the age of open data
* Playing with the emotions of the electorate / Facebook 2016 / Election 2020?
* Role of Tech in controlling/spreading fake news

### Cloud based resources 
* Introduction to current scalable technologies to handle and analyze Big Data.
* Managing large relational databases using SQL
* Options: Google, Amazon, Microsoft

### Career
* Cos we gotta make munny!
* What are your options? 
* Money, Location, Satisfaction --> Can we get all 3? 

### Continuing Education
* There is no way we can cover everything there is to Data Science in 1 (or 2) classes. 
* You have to find things that you want to work on. 
* Start building your own library of resources
* Increasing your Google-fu

---

# Class Organization

How the heck are we going to accomplish all that!?

Step 0: Review [the syllabus](../syllabus_485_s20.html). 

In the workplace you don't get homework assignments. You work on larger projects typically broken down into smaller pieces with their own due dates. It is common also to be working on multiple projects at the same time. 

This class is semi-unstructured, meaning there is a combination of standard homework assignments, and several ongoing / multi-stage activities that we'll be working on throughout the semseter.  This is unlike the modular approach of MATH 456. Throughout the semester we will be engaging in the following: 

Where possible, I will create a "standard" homework assignment - such as the [one due this week](hw/hw00-getting-started.html). Otherwise, you'll notice that the **Assignments** column is a list of items with due dates. Larger tasks are broken into more manageable tasks. 

Examples of ongoing projects include: 

* Reflecting and discussing the readings.
    - This will be as blog posts on your website, and discussions in Slack/class. 
* Learning more and sharing a DS topic that interests you
    - Blog posts / discussions in Slack/class.
    - You will pick a case study from DDS that you will present to the class. 
* Collaboration (potentially)
    - You will build and contribute a tutorial/lesson/example of a topic that interests you. 
    - Eg: Shiny Dashboard, Blogdown CV, Image classification lesson, 
    - You will get a chance to present/teach this to the class. 

---

# General Outline of Topics
Totally subject to time constraints and how the class unfolds, but generally be covered in the following order. 

1. Creating personal webpages. 
    - You'll be heading into the career world soon enough. Now is the time to start playing around with your own site and building your DS portfolio. 

2. What is Data Science? Who is doing Data Science? What's hot right now? 
    - Another look at the field you are studying. 
    - Building connections into this community. 
    - What is your Data Science profile? 
    
3. Analying public opinion using historical Tweets
    - This is the topic of the joint project. 
    - You will need to create a developer account
    - This is beta testing, we are doing a dry run so that we know what we're doing before we work with others. 

4. Statistical Learning
    - Linear Regression, from a different viewpoint
    - Classification using multiple classifiers
    - Resampling methods (Cross Validation)
    - Tree based methods

5. Ethics of Algorithms, Machine Learning, Big Data. 
    - Lots of reading, reflection, and looking for examples in every day occurrences. 
    
6. Big Data
    - What's the big deal about big data? 
    - Big Data Ecosystem
    - SQL for managing large datasets


And likely spattering of random other topics here and there. 
