---
title: "Class meeting 03-10-2020"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
---

# Overview

## Reference docs
Associated Reading: ISLR Ch 3 Introduction, 3.4

## Goals
* Learn how to assess a posed research question for “analyzability”
* Identify at least one RQ per team that can be answered given the data available. 

# Outline
* Talk through ISLR Ch 3 :heavy_check_mark:
* Review Twitter project docs. :heavy_check_mark:
* Walk through examination and questioning of Markley. :heavy_check_mark:
* Student examinations -  Gulnar & Swindle :heavy_check_mark:
* Breakout rooms - pair discussion on individual pairs :x:
* Share out - what further questions do you have? :x:


# Deliverables
* Review the student questions from your POLS team. Assess the questions for “analyzability”
* Provide feedback as comments in the documents directly.  
* Due Wed before 7pm

# Notes from ISLR Ch 3 (Intro & 3.4)
How would we answer this question? _Is there a relationship between advertising budget and sales?_

* Break down into region? 
* Correlate to sales in that region

* Determine data types
    - Both are continuous. 

* What is the mathematical model? 
    - Correlation between budget & sales. 
    - Budget as IV (x1)
    - Sales as IV (y)
    - Sales ~ f(Budget)
    - Sales ~ budget + region + advertisement mode

Y = B0 + x1B1 + x2B2 

* What is the appropriate visualization and analysis technique? 
    - Correlation coefficient
    - Scatterplot
    - (Multiple) Regression model 


* How strong of a relationship is there? 
    - Measures of model fit (low RMSE), Adjusted R2
    - Estimate, CI and pValue of b1 (estimate of impact of budget on sales)

* How accurately can we estimate the effect of each medium on sales?
    - CI / margin of error for a single beta for that medium (TV/Radio/Newspaper)


* How accurately can we predict future sales?
    - Different than predicting an average sale
    - Regression models are estimating the average values E(Y|X)
    - Individuals [f(x) + e] are more variable than averages [f(x)]
