---
title: "Class meeting 03-12-2020"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
---

# Overview

## Reference Docs
* Twitter project docs
* Project overview

## Goals
* Identify new data management tasks necessary for project development
* Assign tasks to different team members. 
* Set a timeline for deliverables 

## Housekeeping

* HW 05 was to be due on Friday. Officially move the due date back to Wed 3/25 
    - Knit to PDF, submit in Google Drive
* Update on Poster presentation --> Virtual conference presentation. Time TBD. 
* Status of R twitter tutorials? 
    - I tried some of them, and they all needed an API key. 
    - They should be posted on your website so I can share that link with the POLS students. You can’t view an HTML file in Google Drive without downloading. 
* Recap the outcomes of the POLS class last night. 
    - Examine the documents for the groups that I was able to talk to. 


# Project development

* Identify new DM tasks for project development 
* Assign tasks to different team members. 
* Set a timeline for deliverables 



# Deliverables (Due 3/27)

## Robin
* Get the twitter data & dm file into a github repo that is shared with the class. 
* I control the master branch, and handle all PR’s 


## Students

* Fork the twitter collab data repo
* Put your name on the project document that you’re assigned to.  
* Schedule a meeting time with your group the week after spring break to talk over the research question. The sooner you can do this the better. 
    - When you meet with them, write up a summary in your own words about what the research question is about. You will turn this in. 


Data management tasks necessary for project development (point person)

* (Tanya) Applying sentiment scores to each tweet.
* (Brandon) Create indicator or categorical variable for presence of keywords in text. 
* (Olivia) Get data for a larger time frame for an individual (or a few) accounts such as @PG&E
* (Irf) Look into more detail about how to get any sort of location (even regional) data out of tweets. 
* (Madeline) Can we identify user accounts that are ‘official’ news organizations? 
* (Kris) What does “Verified” actually indicate? 
* (Kaleb) What information is contained in the “media variables”? 


