---
title: "Week 14: Tree Based Models"
date: "`r paste(Sys.Date())`"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
---

# Learning Path

### Where we've been

* Multivariable model building using linear and logistic regression. 
* Basic concepts surrounding flexible vs rigid, parametric vs non-parametric estimates of $f$. 
* Basic concepts of prediction and classification. Target measures of fit. 
* Wrangling and exploring text data
* Classification models other than logistic regression. Starting simple with discriminant analysis and naive Bayes. (ISLR Ch 4)
* Employing resampling methods such as cross validation to improve our prediction accuracy (ISLR Ch 5)
* Estimating accuracy using the bootstrap (ISLR Ch 5.2)
* Working with the `caret` package to conduct a machine learning algorithm to classify data under a variety of models. 

### Where we're at

* Topic modeling of text data - making predictions using text.  (Skipping because of time constraints)
* Ethics of Predictive models and artificial intelligence. 
* Tree based methods for classification (ISLR Ch 8)


----

# Goals for this week. 

* Project - start wrap up/decide on what results to present. 
* Start reading [Weapons of Math Destruction (WMD)](https://chico-primo.hosted.exlibrisgroup.com/permalink/f/jik37n/01CALS_ALMA71384958140002901)
* Start reading ILSR Ch8 on Tree based models. 
    - Work through questions as a group in [[these notes]](lec09-tree-models.html)
    - Last homework assignment. Due 5/15. [[Github repo assignment link TBD]]()

## WMD Reading Schedule
Each set of 2 chapters has a few [reflection questions](../read/WMD_Discussion_Questions.html). Choose one of these discussion questions to answer in your Learning Journal by the due date. We will share out in class each day next week. 

* Intro & Ch 1 - Due 5/4 [In class discussion on Tue]
* Ch 2 & 3  - Due 5/6 [In class discussion on Thu] 
* Ch 4 & 5 OR 6 & 7 - Due Fri 5/15 


----

# Tuesday
No class.

----

# Thursday

## Reading on ethics of algorithms

* I notified you via Slack on Tuesday to start reading/listening to the WMD book.
    - The reading & writing assignment schedule is at the top of this page. 
    - First writing assignment due this Friday.  
* Additional (optional) readings on ethics & algorithms have been added to the [materials](materials.html) page. 

## Project updates

* Wrapping up EDA, decide on what graphics that tell your story the best. 
* Final draft of presentations due this upcoming Sunday. 
* One more round of peer review, to help you finalize your presentations. 


## Tree based methods

* Just an introduction today, following ISLR Ch 8.1
* Notes are linked here and on the materials page. [[HTML]](lec09-tree-models.html) or the [[RMD]](lec09-tree-models.Rmd) if you want to use it to take notes on. 
* Collaborative notes session - Each breakout room will have 4 questions to answer.
    - We will return and each group shares out their answers with the rest of the class. 
    - You will turn in your answers as part of your homework. 
    - This RMD document will be included in the github classroom link once it's created. 





