---
title: "Week 15: Tree Based Models"
date: "`r paste(Sys.Date())`"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
---

# Learning Path

### Where we've been

* Multivariable model building using linear and logistic regression. 
* Basic concepts surrounding flexible vs rigid, parametric vs non-parametric estimates of $f$. 
* Basic concepts of prediction and classification. Target measures of fit. 
* Wrangling and exploring text data
* Classification models other than logistic regression. Starting simple with discriminant analysis and naive Bayes. (ISLR Ch 4)
* Employing resampling methods such as cross validation to improve our prediction accuracy (ISLR Ch 5)
* Estimating accuracy using the bootstrap (ISLR Ch 5.2)
* Working with the `caret` package to conduct a machine learning algorithm to classify data under a variety of models. 

### Where we're at

* Ethics of Predictive models and artificial intelligence. 
* Tree based methods for classification (ISLR Ch 8)


### Goals for this week. 

* Project - Peer review final slides
* Reading Weapons of Math Destruction 
* Continue through ILSR Ch8 on Tree based models. 
    
---

# Materials

* [[WMD Discussion Questions]](https://norcalbiostat.github.io/ADS/read/WMD_Discussion_Questions.html)
* Lecture notes on Tree based models [[HTML]](lec09-tree-models.html)
* CART homework [[HTML]](../hw/hw09-CART-assignment.html) [[Github repo]](https://classroom.github.com/a/PHgPJN70)
* ISLR [[video lectures]](https://www.youtube.com/watch?v=6ENTbK3yQUQ&list=PL5-da3qGB5IB23TLuA8ZgVGC8hV8ZAdGh).

----

# Tuesday

* Discussing WMD Intro & Ch1. What makes a WMD? 
* Best (Agriculture) practices - keep those trees pruned. Better for the tree, better for the fruit. 
* Remember you're responsible for all the questions from the book, not just the ones that you answered in class. 

----

# Thursday

* End of the semester Learning Journal entries: Reflections on the past 16 weeks. 
    - [Complete theBridge](https://norcalbiostat.github.io/MATH315/lecture/321_Bridge.html). 
    - Thinking Routine [I used to Think... Now I think...](used_to_think.html)
    - Lastly, and this is for my future course development. Answer the following two questions: 
        - What is one thing you are glad you learned in this class? 
        - What is one thing you wished you had learned in this class? 
* Discussing WMD CH 2 & 3. 
* Methods to enhance decision trees. 




