---
title: "Week 9 notes"
output:   
  html_document: 
    highlight: tango
    theme: yeti
    toc: yes
    toc_float: true
---

_A video recording of this document has been created and posted in google drive_

# Housekeeping

## Goals
Imagine that we had class as scheduled on Tuesday 3/24. This is what we would have covered.

* COVID-19 related course changes
* Project tasks
* Natural Language Processing


This week we are going to complete steps to keep this project moving forward, and start to learn a bit about text processing, sentiment analysis, and natural language processing. 


## COVID-19 related course changes

* I will still be holding class virutally, during normal class times. 
  - I am aware that there are times where you may not be able to make it to class due to caring for others during this time. As with 456, grace is given, but I ask that you try your best to be there.
  - When you can't make it, you still need to check the course webpage and Slack to catch up on what you missed. 
* The topics have changed slightly. Both to remove the amount of content to reflect this difficult time and to adjust for the language processing topics coming up as part of the project. 
  - The schedule on the course website has been updated to reflect our tentative topic schedule. 
  

## Other housekeeping
* Assignments prior to break are closed for submission.
* The only exception will be the Twitter tutorial. 
  - I'm relying on you all for this. I can't do my job until you do yours. 
* Due Wed 3/25 
  - **EOD (midnight)** HW 05. Compile to PDF, upload to Google Drive. 
  - **EOB (5pm)** Read the notice in the POLS Slack channel about switching topics. Post your opinions with justification.

----

# Tuesday 3/24/2020


## Recap of project tasks

Data management tasks necessary for project development. 
Each task has been assigned to a point person. That person is responsible for adding their content to the specified pages on the [project repo](https://github.com/DATA485-S20/campfire_tweets). 

#### Tasks we know how to do and can get done now. 

* (Brandon) Create indicator or categorical variable for presence of keywords in text. 
    - New RMD file under `code`. Add a link on the tutorials page. 
* (Irf) Look into more detail about how to get any sort of location (even regional) data out of tweets. 
    - Add info to `data.Rmd`
* (Madeline) Is there something in the tweet metadata that identifies 'official' news organizations? 
    - Add info to `data.Rmd`
* (Kris) What does "Verified" actually indicate? 
    - Add info to `data.Rmd`
* (Kaleb) What information is contained in the "media variables"? 
    - Add info to `data.Rmd`
* (Collin) See if you can apply something like [this process](https://www.kaggle.com/aruncps/basic-setup-to-import-the-json-files) to extract the JSON data into R. 


#### Tasks we know how to do but need to be strategic about depending on group decisions. 
* (Olivia) Get data for a larger time frame for an individual (or a few) accounts such as @PG&E
    - Review the research question topics and talk with individual groups to find out what topics we'll need longer term information about. Note which group needs which information. 
    - Write this as a list in the #data-team channel in POLS Slack. 


#### Tasks we need to learn how to do
* (Tanya) Applying sentiment scores to each tweet.
  - Try to blindly use the [SentimentAnalysis](https://cran.r-project.org/web/packages/SentimentAnalysis/vignettes/SentimentAnalysis.html) to score a tweet. Not sure if this is *the* package we'll use, but it's worth poking at it. 
  - Make a new RMD file for this work. We'll build off of it and add it to the project website. 
  - Ask me in Slack if you get stuck in reading or applying parts of that vignette. 
  

----


## Learning Content

### Natural Language Processing

Each time I encounter this topic, the algorithms, packages and things that can be done to text keep improving. 

* Articles I came across that explain this topic and found that they read easily. 
  - [What is NLP (overview)](https://www.lexalytics.com/lexablog/what-is-natural-language-processing)
  - [Machine learning for NLP](https://www.lexalytics.com/lexablog/machine-learning-natural-language-processing)
* CRAN task view: [All things NLP related in R](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html)
* DataCamp tutorial Part I: [Text mining and Exploratory analysis](https://www.datacamp.com/community/tutorials/R-nlp-machine-learning)
* DataCamp tutorial Part II: [Tidy sentiment analysis](https://www.datacamp.com/community/tutorials/sentiment-analysis-R)
* DataCamp tutorial Part III: [Predictive analytics](https://www.datacamp.com/community/tutorials/predictive-analytics-machine-learning)


#### Disclaimer

* Text processing/NLP *can* be done in R, but using interfaces to other languages. This is one of those places where Python has the stronger capabilities. We aren't going for anything extremely fancy in this project, so R will suffice. 


----

## Deliverables 


### Dr. D (Due 3/29)

* Modify twitter project data repo to reflect project topic changes. 
* Make video for pols students on how they can collect their own twitter data using DS student tutorials.

### Students 

Suggestion: View this file in github, copy the md text and make it a todo list for yourself if the assignment tracker isn't sufficient. 

#### (Due 3/28)

1. Fork the twitter project data repo https://github.com/DATA485-S20/campfire_tweets.
2. Address my new comments in your twitter tutorial repo. These should be as issues on lines directly. 
    - If the project tutorial that you posted on your personal page is different than the one that's in the team repo please let me know and I will review yours separately. 
    - Add your tutorial HTML link to your name on the front page then submit a PR. 
3. Meet with your group this week to talk over the research question you will be working on. 
    - You should be meeting together at least once per week. More if you cannot manage to collaborate effectively through Slack asynchronously. 
    - You are required to keep a task list for the project. What are you doing and by when, what are they doing and by when. This list is to be [posted in your group slack channel](https://slack.com/help/articles/203950418-Use-posts-in-Slack), making sure that shared editing is enabled. Check boxes lists can be created using `* [ ] ` (mind the space after ]) and `* [x] `
4. Your assigned project management task from the above list. 
    - If you finish fast, and I know which ones will, help Olivia and Tanya. 


#### (Due 3/30)
5. LJ entry. Look back at what you said you were going to do in lec02 notes. Were you doing it before all hell broke loose? Give yourself permission _in writing_ to slack off on this aspect of your external learning for the time being.   
6. Blog post. This is written and posted on your website, then linked into #state-of-ds Slack channel.
    - What role are data scientists playing right now on the battle against COVID-19? Provide evidence for your claim using links to pages, tweets, stories, projects that are going on right now. 
    - If you had infinite time and no classwork, what current project tackling the pandemic would you want to be involved in? 

#### (Due 4/1)
7. Post discussion - Comment on at least one of your classmates posts.   
8. Read the 2 NLP articles above and [answer these few questions](https://forms.gle/rofwbaTqGLxiK9br8). 


-----

# Thursday 3/26/2020

## Goals

* Address questions and concerns about deliverable list
* Make progress on this work. 


## New content

* Guidance on project or tutorial development - start small with a clear message. The [LA Times Coronavirus in CA report](https://www.latimes.com/projects/california-coronavirus-cases-tracking-outbreak/). 
