---
title: "Assignment: Getting Started"
output:   
  html_document:
    theme: yeti
    highlight: tango
    css: ../style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Materials

* Familarize yourself with the class website navigation. Make sure you can find
    - The weekly/topic overview grid
    - The due date for this assignment
    - Full list of lecture materials, homework, additional readings
    - Calendar of events, & the toggle between the class calendar and the DSI calendar
    - The project page where all content related to the joint project will be presented. 
  
* Obtain a copy of Doing Data Science (DDS) by O'Neil & Schutt. Through our library there is at least one hard copy available in the Library, and an online version it appears we have free access.
    - Our first reading will be due Tuesday 1/31
* Download a copy of ISLR 7th edition http://faculty.marshall.usc.edu/gareth-james/ISL/ 
    - There are cheap print version avaible. I have no idea what's been updated in each edition aside from corrections.  
* Prepare to obtain a copy of Weapons of Math Destruction (WMD) by Spring Break. There also should be a few copies in the library. 



## Programs

Update R (3.6+) & R Studio (latest)


## Hack MD

We will be using HackMD as a place for collaborative notes. These notes will be locked to our class (using your github user accounts). 

1. Sign in to HackMD using your Github account. Just to make sure it works and you know where to go. We'll use this on Tuesday of week 2. 


## Slack

1. Join our Slack channel csuc-ads.slack.com by clicking on the invite link in your campus email account
2. Download & Install both the phone app, and the desktop app. You must have at least the desktop app at minimum.
3. PM Dr. D with your github username. You will be added to the class organization.  
4. Introduce yourself in the #introductions channel. You'll do something similar in 456, so this is brief. 
    - What do you want to get out of this class?
    - What are you worried/concerned about with this class? (after Tuesday's orientation)


## Github

Once added to the class Github organization, find the `class-logistics` repository. You have been granted **write** access to this repo. You will be adding information to the README file a few times. Since you have write access, you could access the master branch directly, but we are going to work on how to work in git as a team using _branches_. 


1. Click "Branch: master" button on the left side, next to "New pull request" button. 
2. Make a new branch by typing the branch name in the text box. If it does not automatically switch you to that branch, click the branch button again and select your branch
3. Click on the pencil icon in the top right corner. This will put the file in edit mode (only works for code files like `.md` and `.Rmd`)
4. Add your edits.
5. Write a commit message below and commit your changes to your branch
6. Create a pull request (PR). Make sure the arrow goes from your branch to the master branch
7. Delete your branch.

**Learn more about using branches and how to manage branches at the command line**: https://www.atlassian.com/git/tutorials/using-branches

Pre-req: Working with remote repositories first (https://www.atlassian.com/git/tutorials/syncing)



## Twitter

1. Make a Twitter account. When in doubt, link it to your campus email address. 
We'll do more with this later. For now it's yours to connect to the greater DS community. 
2. Add your Twitter handle to the README in the `class-logistics` repo using branch/PR.


## Project

Fill out this Google Form so we can figure out teams for the joint project
https://forms.gle/GMr4xNd517ny8H496


## Learning Journal (LJ)

If you opted to create an electronic learning journal, PM Robin a link to your LJ in Slack. 


