---
title: "Assignment: Building your DS portfolio"
output:   
  html_document:
    theme: yeti
    highlight: tango
    css: ../style.css
---

# Part I. Demo Sites

* Using the relevant lecture notes and starter code from Github Classroom, create a basic/demo website using both R Markdown and Hugo/Blogdown.
    - Put your published site URL in your repo's description. 
    
### Submission
These will be checked off in Github Classroom. 

# Part II. Start your own site

You can choose to use either method (Rmarkdown/Blogdown). 
This repo should be in your own personal github account, not the DS classroom account. 
By the due date have the following completed: 

* A page/section with brief info about you
  - Name
  - Contact info
  - Github repo
  - Short Bio (About me)

* A page/section to showcase projects
  - Link to at least one recent project. 
  
* A page/section to blog, write tutorials, share stories. 
  - A "Hello world" example post. 

* Edit the repo description, and/or the `README.md` file to include the URL of your live site. 

I'm happy to help brainstorm style/formats for Rmarkdown websites. 
Look at all my class websites to see slightly different ways to organize content. 


### Submission

Add your public website URL to the README in the `class-logistics` repo using a pull request.

