---
title: "Political Opinion on Natural Disasters"
output: html_document
---

_Add overview, learning objectives, and a timeline_

# Overview

First hand experience working on a research team where the divisions of expertise are pretty clear. POLS graduate students are the subject matter experts, DS students are the data experts. Little bit of cross-topic learning, lots of collaboration. Joint presentation at the end of the semester. 


# Timeline

* Week 2: Collaboration Logistics. These orgs are invite only and tied to your campus email. 
    - Slack workspace: pols624-ds-project.slack.com
    - Google Drive: https://drive.google.com/drive/folders/1LtH-9IEYSCCLYIPaQzoAscLf9gyWHcRU
    - Introduce POLS students to the project, DS presentation to get buy in. 
* Week 3 - 6: POLS students get an introduction to R, and to the shape of Twitter Data. 
* Week 5(?): Intro DS students to social research using Twitter.
    - Read over the types of Twitter analysis research done in the social sciences. (`Twitter project docs` folder in Google Drive)
    - You will each be assigned to read a research article that uses Twitter to examine opinions. Your goal is to summarize and explain to the class, the methods they used to 1) extract twitter data, and 2) what analysis was performed. 
* Week 6: DS Students write up tutorials on how to get and use different types of twitter data. 
    - Started here: [twitter info.md](https://hackmd.io/@norcalbiostat/data485-twitter)
* Week 7: Draft research question development. 
    - POLS students draft research questions
    - DS students provide feedback and ask operationalizing & refinement questions. 
    - Collect student schedule data for team formation https://forms.gle/GMr4xNd517ny8H496 
* Week 8: POLS students decide on a RQ, and start working on background & introduction slides. 
    - Team formation based on schedule compatability. 

_campus is shut down due to COVID-19. Schedule changes, topics change, groups change_

* Week 11: Sunday 4/5 - Up to slide 5 (background & introduction)
* Week 12: Sunday 4/12 - Up to slide 8 (methods)
* Week 13: 
    - Sunday 4/19 - Up to univariate results
    - Wednesday 4/22 - Peer review of other teams slides
* Week 14: Sunday 4/26 - Up through bivariate results
* Week 15:
    - Sunday 5/3 - Finish it out, discussion & conclusion
    - Wednesday 5/6 - Peer review of other teams slides
* Finals week: 
    - Either Mon 5/11 or Wed 5/13, 6-8pm. Confernece presentations. 



